// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: armors.sql

package sql

import (
	"context"
)

const ListArmors = `-- name: ListArmors :many
SELECT id, armor_type_id, name, body_part, price, weight, maxhp, maxmp, evasion, magic_defense, power_defense, run_speed, walker_speed, updated_at, created_at FROM armors
`

func (q *Queries) ListArmors(ctx context.Context) ([]Armors, error) {
	rows, err := q.db.Query(ctx, ListArmors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Armors{}
	for rows.Next() {
		var i Armors
		if err := rows.Scan(
			&i.ID,
			&i.ArmorTypeID,
			&i.Name,
			&i.BodyPart,
			&i.Price,
			&i.Weight,
			&i.Maxhp,
			&i.Maxmp,
			&i.Evasion,
			&i.MagicDefense,
			&i.PowerDefense,
			&i.RunSpeed,
			&i.WalkerSpeed,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
