// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sql

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type Gender string

const (
	GenderM Gender = "m"
	GenderW Gender = "w"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender
	Valid  bool // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type Accounts struct {
	ID         int32
	Nickname   string
	Password   string
	Email      string
	LastActive sql.NullTime
	LastIp     sql.NullString
	UpdatedAt  time.Time
	CreatedAt  time.Time
}

type Armors struct {
	ID           int32
	ArmorTypeID  sql.NullInt32
	Name         string
	BodyPart     string
	Price        int32
	Weight       int32
	Maxhp        int32
	Maxmp        int32
	Evasion      int32
	MagicDefense int32
	PowerDefense int32
	RunSpeed     int32
	WalkerSpeed  int32
	UpdatedAt    time.Time
	CreatedAt    time.Time
}

type ArmorsType struct {
	ID          int32
	Name        string
	Description string
	UpdatedAt   time.Time
	CreatedAt   time.Time
}

type Characters struct {
	ID           int32
	AccountID    sql.NullInt32
	ClanID       sql.NullInt32
	ClassID      sql.NullInt32
	Name         string
	Level        sql.NullInt32
	Maxhp        sql.NullInt32
	Curhp        sql.NullInt32
	Maxmp        sql.NullInt32
	Curmp        sql.NullInt32
	Acc          sql.NullInt32
	Str          sql.NullInt32
	Con          sql.NullInt32
	Dex          sql.NullInt32
	Men          sql.NullInt32
	Wit          sql.NullInt32
	Critical     sql.NullInt32
	Evasion      sql.NullInt32
	MagicAttack  sql.NullInt32
	MagicDefense sql.NullInt32
	MagicSpeed   sql.NullInt32
	PowerAttack  sql.NullInt32
	PowerDefense sql.NullInt32
	PowerSpeed   sql.NullInt32
	RunSpeed     sql.NullInt32
	WalkerSpeed  sql.NullInt32
	Gender       NullGender
	Exp          sql.NullString
	UpdatedAt    time.Time
	CreatedAt    time.Time
}

type Clans struct {
	ID                  int32
	Name                string
	Motto               sql.NullString
	Level               sql.NullInt32
	ReputationScore     sql.NullInt32
	LeaderID            int32
	MaxOnlineMember     sql.NullInt32
	PrevMaxOnlineMember sql.NullInt32
	UpdatedAt           time.Time
	CreatedAt           time.Time
}

type ClansNotice struct {
	ID        int32
	ClanID    sql.NullInt32
	Notice    string
	IsActive  sql.NullBool
	UpdatedAt time.Time
	CreatedAt time.Time
}

type Classes struct {
	ID           int32
	RaceID       sql.NullInt32
	Name         string
	Acc          int32
	Str          int32
	Con          int32
	Dex          int32
	Men          int32
	Wit          int32
	Critical     int32
	Evasion      int32
	MagicAttack  int32
	MagicDefense int32
	MagicSpeed   int32
	PowerAttack  int32
	PowerDefense int32
	PowerSpeed   int32
	UpdatedAt    time.Time
	CreatedAt    time.Time
}

type Races struct {
	ID          int32
	Name        string
	Description sql.NullString
	UpdatedAt   time.Time
	CreatedAt   time.Time
}

type Weapons struct {
	ID           int32
	WeaponTypeID sql.NullInt32
	Name         string
	Price        int32
	Weight       int32
	Acc          int32
	Str          int32
	Con          int32
	Dex          int32
	Men          int32
	Wit          int32
	Critical     int32
	MagicAttack  int32
	MagicSpeed   int32
	PowerAttack  int32
	PowerSpeed   int32
	UpdatedAt    time.Time
	CreatedAt    time.Time
}

type WeaponsType struct {
	ID          int32
	Name        string
	Description sql.NullString
	UpdatedAt   time.Time
	CreatedAt   time.Time
}
