// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sql

import (
	"context"
)

type Querier interface {
	CreateWeapons(ctx context.Context, arg CreateWeaponsParams) error
	CreateWeaponsType(ctx context.Context, arg CreateWeaponsTypeParams) error
	DeleteWeaponsType(ctx context.Context, id int32) error
	GetWeaponsTypeByID(ctx context.Context, id int32) (WeaponsType, error)
	GetWeaponsTypeByName(ctx context.Context, name string) (WeaponsType, error)
	ListAccounts(ctx context.Context) ([]Accounts, error)
	ListArmors(ctx context.Context) ([]Armors, error)
	ListCharacters(ctx context.Context) ([]Characters, error)
	ListClans(ctx context.Context) ([]Clans, error)
	ListClasses(ctx context.Context) ([]Classes, error)
	ListRaces(ctx context.Context) ([]Races, error)
	ListWeapons(ctx context.Context) ([]ListWeaponsRow, error)
	ListWeaponsType(ctx context.Context) ([]WeaponsType, error)
	UpdateWeaponsType(ctx context.Context, arg UpdateWeaponsTypeParams) error
}

var _ Querier = (*Queries)(nil)
