// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: races.sql

package sql

import (
	"context"
)

const ListRaces = `-- name: ListRaces :many
SELECT id, name, description, updated_at, created_at FROM races
`

func (q *Queries) ListRaces(ctx context.Context) ([]Races, error) {
	rows, err := q.db.Query(ctx, ListRaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Races{}
	for rows.Next() {
		var i Races
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
